### PR TITLE
change precision EPSILON in C code

### LINKED ISSUE #93: Not in simplex -- two sets of largely different sizes
I am trying to calculate the EMD of two sets. When one set has a few hundred entries and the other has only 2, the EMD calculation fails and returns Problem Infeasible.

** SEE BELOW COMMENT FOR FIXED SCRIPT ** 

**Expected behavior**
Should return EMD around 1, instead says that the sets spherEng1 and pencilEnergy are not in the simplex

**Screenshots**
Here is comparing the EMDs calculated for less densely tiled to most densely tiled (number of particles = number of segments) with the two element set
image

**Desktop (please complete the following information):**
 - OS: [MacOSX]
 - Python version [3.6]
- POT installed with pip

>>> import platform; print(platform.platform())
Darwin-16.7.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
('Python', '2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
>>> import numpy; print("NumPy", numpy.__version__)
('NumPy', '1.15.4')
>>> import scipy; print("SciPy", scipy.__version__)
('SciPy', '1.1.0')
>>> import ot; print("POT", ot.__version__)
('POT', '0.5.1')

### PR DESCRIPTION
**Pull request by ncourty**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and context / Related issue

Problem INFEASIBLE cast where it should not happen.

Fixes https://github.com/PythonOT/POT/issues/126

Fixes #93 

## How has this been tested (if it applies)

The minimal code to repdroduce the bug is now working.
A user tested on its own data and now the problem is also working

## Checklist

- [X] The documentation is up-to-date with the changes I made.
- [X] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [X] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

File: ot/lp/network_simplex_simple.h [hunk 1]
```diff
@@ -34,7 +34,8 @@
 #endif
 
 
-#define EPSILON 2.2204460492503131e-15
+//#define EPSILON 2.2204460492503131e-14
+#define EPSILON 1.1e-7
```
Comment (agramfort) [inline ot/lp/network_simplex_simple.h:38]: maybe you use FLT_EPSILON from cmath but it's probably good enough

File: ot/lp/network_simplex_simple.h [hunk 2]
```diff
@@ -35,6 +35,7 @@
 
 
 #define EPSILON 2.2204460492503131e-15
+//#define EPSILON 1.1e-7
```
Comment (rflamary) [inline ot/lp/network_simplex_simple.h:38]: You can remove now

File: ot/lp/network_simplex_simple.h [hunk 3]
```diff
@@ -1507,7 +1508,7 @@ namespace lemon {
 			if( retVal == OPTIMAL){
                 for (int e = _search_arc_num; e != _all_arc_num; ++e) {
                     if (_flow[e] != 0){
-                        if (abs(_flow[e]) > EPSILON)
+                        if (fabs(_flow[e]) > _EPSILON)
```
Comment (rflamary) [inline ot/lp/network_simplex_simple.h:1511]: maybe add a comment to say that it was switched to _EPSILON due to numerical problems and refer to the Issue Number
